### ISSUE TITLE
개발환경을 설정한다.

### ISSUE THREAD

**Issue by 4BFC** [4BFC/EditorTool#1]
### ⚠️Issue
- 개발을 위한 개발환경 설정

### ✏️Task
- [x] npm으로 CRA를 세팅 한다.
- [x] TypeScript를 세팅 한다.
- [x] SCSS를 세팅한다.

### 🗓Next Task
- [x] #3
- [x] 페이지를 선별하고 디렉토리 구조화 한다.
