### ISSUE TITLE
Editor 페이지에서 분리 해야 할 컴포넌트를 분리한다.

### ISSUE THREAD

**Issue by 4BFC** [4BFC/EditorTool#5]
### ⚠️Issue
- Editor 페이지에서 Editor영역을 분리한다.

### ✏️Task
- [x] #6
- [x] interface를 적용해서 컴포넌트를 생성, 추가하는 함수를 구현한다.
- [x] editor 컴포넌트가 편집모드, 완성모드 이렇게 두가지로 나뉠 수 있게 CSS를 구현하다.
- [x]  img를 관리하는 데이터 객체를 생성

### 🗓Next Task
- [ ] 할 일
