### ISSUE TITLE
Template에 입력 Tool을 제작한다.

### ISSUE THREAD

**Issue by 4BFC** [4BFC/EditorTool#9]
### ⚠️Issue
- Teemplate에 삭제, 저장을 구현 했으니 입력하는 부분에 Tool을 제작 한다.

### ✏️Task
- [x] Tool 구현
  - [ ] 입력 값이 저장되는 방식을 잘 살펴본다.
    - [x] 선택된 영역에 스타일을 삽입하는 코드 작성
    - [x] 선택된 영역 스타일을 제거하는 코드 작성
    - [ ] 선택된 영역에 스타일이 중복되지 않게 구현
    - [ ] BOM으로 구현한 방식 알아볼 것.
      - [ ] `String.fromCharCode() 또는 유니코드 이스케이프 시퀀스를 사용하는 방식`
  - [ ] enum을 사용해서 효율성 있게 코드를 작성한다.
  - [ ] XSS 공격이 될 수 있는 점을 생각해서 XSS를 방지할 수 있는 방향과 방법을 알아본다.
- [ ] filerbase 연결 및 nodejs 전략 수립 필요
  - [ ] BE를 작업 할 수 있는 디렉토리 구조를 생각해본다.
- [ ] #10
  - [ ] 툴 영역을 제작함에 있어서 다소 시간이 필요하여 excecommand를 사용한다.
  - [ ] md 방식으로 기입을 할 수 있게 한다.
  - [ ]  draft.js를 참고한다.
  - [ ] 드래그엔 드랍을 구현한다.
  - [ ] 좌우측을 드래그해서 크기를 조절 할 수 있다.
  - [ ] 시험지 형태의 템플릿을 구현해본다.

### 🗓Next Task
-
